// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxrTfRnrne4rcZ51YNxONdqh10ba2P5QU',
    appId: '1:516694218193:web:38b25d45ba6f99c71cfcf0',
    messagingSenderId: '516694218193',
    projectId: 'mackenzieacademy-53156',
    authDomain: 'mackenzieacademy-53156.firebaseapp.com',
    storageBucket: 'mackenzieacademy-53156.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzpaH99Fya05AExT3I9tK0uxiXB4WsIw4',
    appId: '1:516694218193:android:0c734a2e7f0a366d1cfcf0',
    messagingSenderId: '516694218193',
    projectId: 'mackenzieacademy-53156',
    storageBucket: 'mackenzieacademy-53156.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpdHA96_TNMOD_jQtdOUP8NyvUyaYgc44',
    appId: '1:516694218193:ios:6cf0e3eb6ce63de61cfcf0',
    messagingSenderId: '516694218193',
    projectId: 'mackenzieacademy-53156',
    storageBucket: 'mackenzieacademy-53156.appspot.com',
    iosBundleId: 'com.example.mackenzieAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpdHA96_TNMOD_jQtdOUP8NyvUyaYgc44',
    appId: '1:516694218193:ios:6cf0e3eb6ce63de61cfcf0',
    messagingSenderId: '516694218193',
    projectId: 'mackenzieacademy-53156',
    storageBucket: 'mackenzieacademy-53156.appspot.com',
    iosBundleId: 'com.example.mackenzieAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxrTfRnrne4rcZ51YNxONdqh10ba2P5QU',
    appId: '1:516694218193:web:3e560452afb856121cfcf0',
    messagingSenderId: '516694218193',
    projectId: 'mackenzieacademy-53156',
    authDomain: 'mackenzieacademy-53156.firebaseapp.com',
    storageBucket: 'mackenzieacademy-53156.appspot.com',
  );
}
